#if !canImport(ObjectiveC)
import XCTest

extension LoggingTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LoggingTest = [
        ("test", test),
    ]
}

extension PostgresDateTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PostgresDateTest = [
        ("test", test),
    ]
}

extension PostgresTimeTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PostgresTimeTest = [
        ("test", test),
    ]
}

extension PostgresTimeWithTimeZoneTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PostgresTimeWithTimeZoneTest = [
        ("test", test),
    ]
}

extension PostgresTimestampTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PostgresTimestampTest = [
        ("test", test),
    ]
}

extension PostgresTimestampWithTimeZoneTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PostgresTimestampWithTimeZoneTest = [
        ("test", test),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LoggingTest.__allTests__LoggingTest),
        testCase(PostgresDateTest.__allTests__PostgresDateTest),
        testCase(PostgresTimeTest.__allTests__PostgresTimeTest),
        testCase(PostgresTimeWithTimeZoneTest.__allTests__PostgresTimeWithTimeZoneTest),
        testCase(PostgresTimestampTest.__allTests__PostgresTimestampTest),
        testCase(PostgresTimestampWithTimeZoneTest.__allTests__PostgresTimestampWithTimeZoneTest),
    ]
}
#endif
