#if !canImport(ObjectiveC)
import XCTest

extension LoggingTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LoggingTest = [
        ("test", test),
    ]
}

extension PostgresTimestampWithTimeZoneTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PostgresTimestampWithTimeZoneTest = [
        ("test", test),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LoggingTest.__allTests__LoggingTest),
        testCase(PostgresTimestampWithTimeZoneTest.__allTests__PostgresTimestampWithTimeZoneTest),
    ]
}
#endif
